In [1]:
import numpy as np
import pandas as pd

# ✅ 1️⃣ NumPy Basics (Day 3-5)

# 1. Create a 1D, 2D, and 3D NumPy array
def create_arrays():
    arry1D = np.ones(4)
    arry2D = np.ones((2,2))
    arry3D = np.ones((3,3,3))
    print(f'1D:\n{arry1D}\n')
    print(f'2D:\n{arry2D}\n')
    print(f'3D:\n{arry3D}\n')

# 2. Find the mean, standard deviation, and max value of an array
def array_stats(arr):
    
    mean_value = np.mean(arr)  # Compute mean
    std_dev = np.std(arr)  # Compute standard deviation
    max_value = np.max(arr)  # Find max value


    # Print results
    print(f"Mean: {mean_value}")
    print(f"Standard Deviation: {std_dev}")
    print(f"Max: {max_value}")
    

# 3. Generate a random NumPy array of shape (3,3)
def random_array():
    arr = np.random.rand(3,3)
    return arr
    

# 4. Flatten a multi-dimensional array
def flatten_array(arr):
     return arr.flatten()

# 5. Reshape a 1D array into a 3x3 matrix
def reshape_array(arr):
    if arr.size != 9:
        raise ValueError("Array must have exactly 9 elements to reshape into (3,3).")
         
    return arr.reshape(3, 3)


# ✅ 2️⃣ Pandas Basics (Day 6-8)

# 1. Load a dataset (train.csv from Titanic or another Kaggle dataset)
def load_data(filepath):
    try:
        df = pd.read_csv(filepath)
        print(f"✅ Successfully loaded dataset with {df.shape[0]} rows and {df.shape[1]} columns.")
        return df
    except FileNotFoundError:
        print("❌ Error: File not found. Check the filepath and try again.")
    except pd.errors.EmptyDataError:
        print("❌ Error: File is empty.")
    except pd.errors.ParserError:
        print("❌ Error: File format is incorrect. Ensure it's a properly formatted CSV.")

# 2. Display the first 5 rows
def show_head(df):
    return df.head(5)

# 3. Find the total number of missing values
def missing_values(df):
    missing_per_column  = df.isnull().sum()  # Missing values per column
    total_missing = missing_per_column.sum()  # Total missing values in the dataset
    print(f"Total Missing Values: {total_missing}\n")
    return missing_per_column 
# 4. Filter rows where Age > 30
def filter_age(df):
    return df[df["Age"] > 30]

# 5. Group data by 'Survived' and get the average fare
def avg_fare_by_survival(df):
    return df.groupby('Survived')['Fare'].mean()


# ✅ Example Usage:
if __name__ == "__main__":
    # Testing NumPy Functions
    print("NumPy Challenges:")
    arr = np.array([1, 2, 3, 4, 5])
    array_stats(arr)
    create_arrays()
    array_stats(arr)
    arr = random_array()
    print(f'Random 3x3 Array:\n{arr}')
    flat_arr = flatten_array(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))
    print(f'flat array:\n{flat_arr}\n')
    print(f'Reshaped 3x3 array:\n{reshape_array(flat_arr)}')

    # Testing Pandas Functions (Make sure you have 'train.csv'!)
    print("\nPandas Challenges:")
    df = load_data("train.csv")
    if df is not None:  # Ensure df is loaded before calling show_head()
        print(show_head(df))
    print("\n")
    print(missing_values(df))
    print("\n")
    print(f'Age over 30: \n{filter_age(df).head(5)}\n\n')  # Show only first 5 rows

    print(f'Survived Average Fare:\n{avg_fare_by_survival(df)}')

NumPy Challenges:
Mean: 3.0
Standard Deviation: 1.4142135623730951
Max: 5
1D:
[1. 1. 1. 1.]

2D:
[[1. 1.]
 [1. 1.]]

3D:
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]

Mean: 3.0
Standard Deviation: 1.4142135623730951
Max: 5
Random 3x3 Array:
[[0.85092261 0.03779701 0.75306635]
 [0.01309025 0.84545281 0.79892022]
 [0.37726011 0.47344164 0.58863401]]
flat array:
[1 2 3 4 5 6 7 8 9]

Reshaped 3x3 array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Pandas Challenges:
✅ Successfully loaded dataset with 418 rows and 12 columns.
   PassengerId  Survived  Pclass  \
0          892         0       3
1          893         1       3
2          894         0       2
3          895         0       3
4          896         1       3

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0
2                     Myles, Mr. Thomas Francis    male  62.0      0      0
3                              Wirz, Mr. Albert    male  27.0      0      0
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1

    Ticket     Fare Cabin Embarked
0   330911   7.8292   NaN        Q
1   363272   7.0000   NaN        S
2   240276   9.6875   NaN        Q
3   315154   8.6625   NaN        S
4  3101298  12.2875   NaN        S


Total Missing Values: 414

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64


Age over 30:
    PassengerId  Survived  Pclass                              Name     Sex  \
0           892         0       3                  Kelly, Mr. James    male
1           893         1       3  Wilkes, Mrs. James (Ellen Needs)  female
2           894         0       2         Myles, Mr. Thomas Francis    male
11          903         0       1        Jones, Mr. Charles Cresson    male
13          905         0       2              Howard, Mr. Benjamin    male

     Age  SibSp  Parch  Ticket     Fare Cabin Embarked
0   34.5      0      0  330911   7.8292   NaN        Q
1   47.0      1      0  363272   7.0000   NaN        S
2   62.0      0      0  240276   9.6875   NaN        Q
11  46.0      0      0     694  26.0000   NaN        S
13  63.0      1      0   24065  26.0000   NaN        S


Survived Average Fare:
Survived
0    27.527877
1    49.747699
Name: Fare, dtype: float64